compressionLevel: 0

enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-changed.cjs
    spec: "https://liuli-tools.rxliuli.com/yarn-plugin-changed/%40liuli-util/plugin-changed.js"

yarnPath: .yarn/releases/yarn-berry.cjs
