name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - rxliuli
body:
  - type: checkboxes
    id: confirm
    attributes:
      label: Confirmation
      options:
        - label: I checked [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)
          required: true
  - type: dropdown
    id: app
    attributes:
      label: The tool/kit where the error occurred
      options:
        - joplin-vscode-plugin
        - joplin-search-integration
        - joplin-batch-web
        - joplin-api
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: logFile
    attributes:
      label: log file
      placeholder: The log file of the plugin, displayed via the `joplinNote.showLogFileDir` command
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: Add any other context about the problem here.
      placeholder:
    validations:
      required: false
