name: 错误报告
description: 创建一个错误报告告诉我发生了什么以便改进
title: '[Bug]: '
labels: [bug, triage]
assignees:
  - rxliuli
body:
  - type: checkboxes
    id: terms
    attributes:
      label: 确认事项
      options:
        - label: 我检查了 [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)
          required: true
  - type: dropdown
    id: app
    attributes:
      label: 发生错误的工具/包
      options:
        - joplin-vscode-plugin
        - joplin-search-integration
        - joplin-batch-web
        - joplin-api
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: 描述这个错误
      placeholder: 清晰简洁的错误描述
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 复现错误的步骤
      placeholder: |
        1. 进入 '...'
        2. 点击'....'
        3. 滚动到 '....'
        4. 看到错误
    validations:
      required: true
  - type: textarea
    id: logFile
    attributes:
      label: 日志文件
      placeholder: 插件的日志文件，通过 `joplinNote.showLogFileDir` 命令显示
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: 其他上下文
      placeholder: 例如系统信息、joplin 版本之类的
    validations:
      required: false
