name: Feature request
description: Suggest an idea for this project
title: "[Feat]: "
labels: [enhancement, triage]
assignees:
  - rxliuli
body:
  - type: dropdown
    id: app
    attributes:
      label: app
      description: What version of our software are you running?
      options:
        - joplin-vscode-plugin
        - joplin-search-integration
        - joplin-batch-web
        - joplin-api
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: existingTool
    attributes:
      label: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternativePlan
    attributes:
      label: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: Add any other context or screenshots about the feature request here.
    validations:
      required: false
