name: 功能请求
description: 为这个项目提出一个想法
title: '[Feat]: '
labels: [enhancement, triage]
assignees:
  - rxliuli
body:
  - type: checkboxes
    id: confirm
    attributes:
      label: 确认事项
      options:
        - label: 我愿意实现它
          required: false
  - type: dropdown
    id: app
    attributes:
      label: 您运行的是我们软件的哪个版本？
      options:
        - joplin-vscode-plugin
        - joplin-blog
        - joplin-batch-web
        - joplin-api
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: 您的功能请求是否与问题有关？请描述。
      placeholder: 对问题清晰简洁的描述，当我想做 [...] 时，总是缺少这个功能
    validations:
      required: true
  - type: textarea
    id: existingTool
    attributes:
      label: 描述您想要的解决方案
      placeholder: 对您想要发生的事情的清晰简洁的描述。
    validations:
      required: true
  - type: textarea
    id: alternativePlan
    attributes:
      label: 描述您考虑过的替代方案
      placeholder: 对您考虑过的任何替代解决方案或功能的清晰简明描述。
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: 其他上下文
      placeholder: 在此处添加有关功能请求的任何其他上下文或屏幕截图。
    validations:
      required: false
